# see: https://scrutinizer-ci.com/docs/configuration/build_reference
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        coverage:
            tests:
                override:
                    - command: composer test-clover
                        coverage:
                            file: tmp/coverage.xml
                            format: clover
        tests: true
    environment:
        php:
            version: "7.2"
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
