name: CI

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
    name: Test PHP ${{ matrix.php-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl
        coverage: none

    - name: Composer install
      run: composer install

    - name: Run PHPUnit
      run: composer run-script test
  
  coverage-php:
    runs-on: ubuntu-22.04
    name: Coverage

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        coverage: pcov

    - name: Composer install
      run: composer install

    - name: Run PHPUnit
      run: composer run-script coverage-clover

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODE_COV_TOKEN }}
        files: ./tmp/coverage.xml
        verbose: true

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        coverage: none

    - name: Composer install
      run: composer install

    - name: Run PHP CodeSniffer
      run: composer run-script cs-checkstyle | vendor/bin/cs2pr

  static-analysis:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
    name: Static Analysis - PHP ${{ matrix.php-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl
        coverage: none

    - name: Composer install
      run: composer install

    - name: Run PHP Analyzer
      run: composer run-script phpstan